### ISSUE TITLE
씬 4 생성

### ISSUE THREAD

**Issue by loonfactory** [Sewing-Game/Sewing#19]
# Overview 
 [wiki](https://github.com/Sewing-Game/Sewing/wiki/Scenes#scenes-4)를 참조 해주세요

# Task list
 - [ ] 마을 레벨 디자인
 - [ ] 씬 4 카메라 설정
 - [ ] 움직임 가이드
 - [ ] 의상실 문 앞에 도착 시 시나리오 1번 실행
 - [ ] 의상실 문 상호 작용
