### ISSUE TITLE
플레이어 생성

### ISSUE THREAD

**Issue by loonfactory** [Sewing-Game/Sewing#23]
# Ovewview 

게임상에서 사용할 플레이어를 만듭니다.

# Task list

- [ ] 움직임
- [ ] 작업대와 상호작용 모션
- [ ] 침대 상호 작용 모션
- [ ] 문 상호 작용 모션
- [ ] 마네킹 상호 작용
- [ ] 쓰러지는 모션
- [ ] 두근두근 모션
