### ISSUE TITLE
Create day 1

### ISSUE THREAD

**Issue by loonfactory** [Sewing-Game/Sewing#29]
# Task list
-  [ ] https://github.com/Sewing-Game/Sewing/issues/18
-  [ ] https://github.com/Sewing-Game/Sewing/issues/19
-  [ ] Create scene 5(scene 5 , [참조](https://github.com/Sewing-Game/Sewing/wiki/Scenes#scenes-5)).
-  [ ] Create scene 6(scene 6 , [참조](https://github.com/Sewing-Game/Sewing/wiki/Scenes#scenes-6)).
