### ISSUE TITLE
Slot Button in Load Scene

### ISSUE THREAD

**Issue by dkdud7622** [Sewing-Game/Sewing#34]
# Concept
-  클릭시 저장된 data를 기반으로 Scene 실행

# 구현 방식
- 타이틀 기본 버튼을 상속 하여 구현([#15](https://github.com/Sewing-Game/Sewing/issues/15))
- 클릭시 저장된 data를 기반으로 게임 Scene  씬을 실행
- 캐릭터이름, 레벨, 골드, 명성, 마을이름, 저장 날짜(게임) 표기

# Precending task

- [ ] https://github.com/Sewing-Game/Sewing/issues/15 

# Task list
- [ ] 디자인
- [ ] 클릭시 이벤트 처리
- [ ] 저장 데이터 표기 및 데이터 처리
