### ISSUE TITLE
씬 5 생성

### ISSUE THREAD

**Issue by dkdud7622** [Sewing-Game/Sewing#39]
# Overview 
 [wiki](https://github.com/Sewing-Game/Sewing/wiki/Scenes#scenes-4)를 참조 해주세요

# Task list
 - [ ] [의상실 내부 레벨 디자인](https://github.com/Sewing-Game/Sewing/issues/35)
 - [ ] [씬 5 카메라 설정](https://github.com/Sewing-Game/Sewing/issues/36)
 - [ ] 씬 5 UI 설정
 - [ ] 튜토리얼 스크립트 참조
