### ISSUE TITLE
Creat Scenes 7

### ISSUE THREAD

**Issue by loonfactory** [Sewing-Game/Sewing#65]
# Overview 

 의상 제작 후 부터 잠들때 까지의 씬입니다. 자세한 내용은  [wiki](https://github.com/Sewing-Game/Sewing/wiki/Scenes#scenes-7)를 참조 해주세요

# Task list
- [ ] 의상 결과에 따라 보상 팝업 실행
- [ ] 보상 팝업 닫은 직후 [대사 스크립트 6](https://github.com/Sewing-Game/Sewing/wiki/Dialogue-Scripts#dialogue-script-7) 실행
- [ ] 골드, 명성, 레벨 UI 설명
- [ ] [대사 스크립트 8](https://github.com/Sewing-Game/Sewing/wiki/Dialogue-Scripts#dialogue-script-8) 실행
- [ ] 시계 UI 설명 
- [ ] 침대 상호작용 활성화
