### ISSUE TITLE
메뉴창 UI 제작

### ISSUE THREAD

**Issue by dkdud7622** [Sewing-Game/Sewing#74]
# Overview 

- 게임 환경 설정을 제어 할 수 있는 메뉴창 입니다.

# Concept

![Image](https://user-images.githubusercontent.com/80615126/202720893-84289361-c7cf-46b6-a7ba-5c278a2bfd0f.png)

# Precending task

- [ ] https://github.com/Sewing-Game/Sewing/issues/41

# Task list

- [x] 디자인
- [ ] https://github.com/Sewing-Game/Sewing/issues/76
- [ ] https://github.com/Sewing-Game/Sewing/issues/75

# 그래픽 리소스
- 팝업 배경 : [참조](https://drive.google.com/file/d/1Ogh1JXj1oF3azGL4-gbE4ixsqkqEFcF9/view?usp=sharing) 
- 종료 버튼 : [참조](https://drive.google.com/file/d/1ozk6VTnAd-iApZl4NBKi2RnEESyPmNnK/view?usp=sharing)
- 폰트 : [DX아기사랑B](https://drive.google.com/file/d/18OkrxwvZmDgEM7LUrCuJmo1sWvlz_DaU/view?usp=sharing)
